# Persistent Volume for Blob Storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blob-storage-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# Blob Storage Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob-storage
  template:
    metadata:
      labels:
        app: blob-storage
    spec:
      containers:
      - name: blob-storage
        image: jpgsilveira/tukano-blobs
        volumeMounts:
        - mountPath: "/tmp/blobs"
          name: blob-volume
      volumes:
      - name: blob-volume
        persistentVolumeClaim:
          claimName: blob-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: blob-storage
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080 
  selector:
    app: blob-storage

# Database Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "tukano"
        - name: POSTGRES_USER
          value: "tukano"
        - name: POSTGRES_PASSWORD
          value: "tukano"
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: ClusterIP
  ports:
  - name: db
    port: 5432
    targetPort: 5432
  selector:
    app: database

# Cache Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: redis
      - args:
        - redis-server
        - --requirepass
        - "key"
---
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  type: ClusterIP
  ports:
  - name: cache
    port: 6379
    targetPort: 6379
  selector:
    app: cache

# Tukano Main Application Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tukano
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano
  template:
    metadata:
      labels:
        app: tukano
    spec:
      containers:
      - name: tukano
        image: jpgsilveira/tukano
        ports:
        - containerPort: 8080        
---
apiVersion: v1
kind: Service
metadata:
  name: tukano
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: tukano